DROP TABLE IF EXISTS growers CASCADE;
DROP TABLE IF EXISTS landholders CASCADE;

CREATE TABLE growers(
id SERIAL PRIMARY KEY, 
category BOOLEAN NOT NULL,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
address TEXT NOT NULL, 
message TEXT NOT NULL);

CREATE TABLE landholders(
id SERIAL PRIMARY KEY, 
category BOOLEAN NOT NULL,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
address TEXT NOT NULL, 
message TEXT NOT NULL,
grower_id INTEGER NOT NULL REFERENCES growers(id) ON DELETE CASCADE);